графика для всех страниц
htmlacademy-htmlcss/1961791-device-33 pull request #3
Opened 2022-01-30 20:41 UTC by KatieZuzukina

2022-01-30 22:43 UTC, KatieZuzukina commented
Сделала дз1 оправила и когда приступила ко второй части заметила еще картинку. Отменила. Все добавила- снова запушила и теперь видно кусочек второго дз. Не обращайте внимание(< link>), не знаю как его скрыть, чтоб Вас не путать.🙈

2022-01-31 13:15 UTC, andreysgra requested changes
Неожиданно у вас изменилась файловая структура проекта. Файлы проекта оказались в папке **project**. Нужно их вернуть обратно, а папку **project** удалить.

---

В целом по заданию выполнено всё хорошо.

2022-01-31 13:15 UTC, andreysgra commented on project/catalog.html
> +            <img class="device-card-image" src="images/catalog/product-1.jpg" width="360" height="380" alt="Любительская селфи-палка">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01): подпись в конце описания должна иметь точку. Точка нужна для интонационной паузы при чтении скринридером.

2022-01-31 13:15 UTC, andreysgra commented on project/catalog.html
> +            <img class="device-card-image" src="images/catalog/product-2.jpg" width="360" height="380" alt="Профессиональная селфи-палка">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 13:15 UTC, andreysgra commented on project/catalog.html
> +            <img class="device-card-image" src="images/catalog/product-3.jpg" width="360" height="380" alt="Непотопляемая селфи-палка">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 13:15 UTC, andreysgra commented on project/catalog.html
> +            <img class="device-card-image" src="images/catalog/product-4.jpg" width="360" height="380" alt="Селфи-палка «Следуй за мной»">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 13:15 UTC, andreysgra commented on project/catalog.html
> +        <img class="footer-contacts-logo" src="images/logo-footer.svg" width="145" height="36" alt="Логотип магазина «Device»">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 13:15 UTC, andreysgra commented on project/index.html
> +          <img class="slider-image" src="images/slider/slider-1.png" width="560" height="560" alt="Квадрокоптер">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 13:15 UTC, andreysgra commented on project/index.html
> +          <img class="slider-image" src="images/slider/slider-2.png" width="560" height="560" alt="Умные часы">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 13:15 UTC, andreysgra commented on project/index.html
> +          <img class="slider-image" src="images/slider/slider-3.png" width="560" height="560" alt="Селфи-палка">
[ALLY-01](https://up.htmlacademy.ru/htmlcss/33/criteries#ALLY-01)

2022-01-31 20:50 UTC, merged